config/routes.rb
Rails.application.routes.draw do

  root 'flights#index'
  resources :bookings, only: [:new, :create, :show, :index]
  resources :passengers, only: [:new, :create, :show]
  resources :flights, only: [:show]

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "destination_airport_id"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  has_many :passengers
  belongs_to :flight
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :destination_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, :through => :bookings

  def self.search(params)
  	if params[:search]
  	  Flight.on_date(params[:date].to_date)
  	  .where(departure_airport_id: params[:departure_airport_id], destination_airport_id: params[:destination_airport_id])
  	  .includes(:departure_airport, :destination_airport)
  	end
  end

  def self.flight_dates
    all.collect { |f| [f.formatted_date, f.date.to_date] }.uniq
  end

  def self.on_date(date)
    # elegant solution from: http://stackoverflow.com/questions/2381718/rails-activerecord-date-between
    where(date: date.beginning_of_day..date.end_of_day)
  end
  
  def formatted_date
    date.to_date.strftime("%m/%d/%y")
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking
  has_one :flight, :through => :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  	@booking = Booking.new
  	@num_passengers = params[:num_passengers]
  	@num_passengers.to_i.times { @booking.passengers.build }
  	@flight = Flight.find(params[:flight_id]) unless params[:flight_id].nil?
    redirect_to root_path if params[:flight_id].nil?
  end

  def create
  	@booking = Booking.create(booking_params)
  	redirect_to @booking
  end

  def show
  	@booking = Booking.find(params[:id])
  end

  def index
  	@bookings = Booking.all
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  	@flights = Flight.search(params)
  	@airports = Airport.all.map { |a| [a.code, a.id] }
  	@dates = Flight.flight_dates
    @num_passengers = (1..4).to_a.collect { |x| [x, x] }
  end

  def show
  	@flight = Flight.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/_booking.html.erb
Booking Number: <%= link_to @booking.id, @booking %><br>
Flight ID: <%= link_to @booking.flight.id, @booking.flight %>
<%= " from #{@booking.flight.departure_airport.code} to #{@booking.flight.destination_airport.code}
     on #{@booking.flight.date.to_date}" %><br />
<%= "Number of Passengers: #{@booking.passengers.count}"%><br />
<% @booking.passengers.each_with_index do |passenger, i| %>
  <%= "Passenger #{i+1}: #{passenger.name} <#{passenger.email}>" %><br />
<% end %>

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
  Booking Number: <%= link_to booking.id, booking %><br>
  Flight id: <%= link_to booking.flight.id, booking.flight %>
  <%= " from #{booking.flight.departure_airport.code} to #{booking.flight.destination_airport.code}
       on #{booking.flight.date.to_date}" %><br />
  <%= "Number of Passengers: #{booking.passengers.count}"%><br />
  <% booking.passengers.each_with_index do |passenger, i| %>
    <%= "Passenger #{i+1}: #{passenger.name} <#{passenger.email}>" %><br />
  <% end %>
  <br>
<% end %>

app/views/bookings/new.html.erb
<h1>Passenger Information</h1>

<%= "Purchasing tickets for #{pluralize(@num_passengers, "passenger")}" %><br />
<%= "Flight ##{@flight.id} from #{@flight.departure_airport.code} to #{@flight.destination_airport.code} on #{@flight.date.to_date}" %>
<hr />
<%= form_for @booking do |f| %>
  
  <%= f.hidden_field :flight_id, value: @flight.id %>

  <%= "Please enter the following information:" %><br />

  <%= f.fields_for :passengers do |passenger_form| %>
    Name: <%= passenger_form.text_field :name %>
    Email: <%= passenger_form.text_field :email %>
    <br />
  <% end %>
  
  <%= f.submit %>
	
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Confirmation</h1>

<hr />
<%= render @booking %>

<%= button_to "Book another flight", root_path, method: 'get' %>

app/views/flights/_flight.html.erb
<%= radio_button_tag 'flight_id', flight.id %>
<%= "#{flight.departure_airport.code} ---> #{flight.destination_airport.code}" %>   
<%= "Departs: #{flight.date.to_formatted_s} - Duration: #{time_ago_in_words(flight.duration.minutes.from_now)}" %><br>

app/views/flights/index.html.erb
<h1>Flights#index</h1>
<%= form_tag(root_path, method: "get") do %>
  <%= hidden_field_tag :search %>
  From: 		  <%= select_tag(:departure_airport_id, options_for_select(@airports)) %>
  To:  			  <%= select_tag(:destination_airport_id, options_for_select(@airports)) %>
  Date: 		  <%= select_tag(:date, options_for_select(@dates)) %>
  No. Passengers: <%= select_tag(:num_passengers, options_for_select(@num_passengers)) %>
  <%= submit_tag("Search") %>
<% end %>

<% if params[:search] && !@flights.empty? %>
  <%= form_tag(new_booking_path, method: "get") do %>
    <%= render @flights %>
    <%= hidden_field_tag :num_passengers, params[:num_passengers] %>
    <%= submit_tag "Select this flight" %>
  <% end %>
<% end %>

app/views/flights/show.html.erb
<%= "Flight: #{@flight.id}
     from #{@flight.departure_airport.code} to #{@flight.destination_airport.code}
     on #{@flight.date.to_date}" %><br />
<%= "Number of Bookings: #{@flight.bookings.count}"%><br />
<% @flight.bookings.each do |booking| %>
  <%= "Booking #{booking.id}: " %><br>
  <% booking.passengers.each_with_index do |passenger, i| %>
    <%= "Passenger #{i+1}: #{passenger.name} <#{passenger.email}>" %><br>
  <% end %>
  <br>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Bookings", bookings_path %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>